
# in the templates via {{ site.myvariable }}.
title: mcshell.net - Веб дизайнер
name: mcshell.net
email: michaelkhamardiuk@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Own website of Michael Khamardiuk
themecolor: #222
baseurl: "/" # the subpath of your site, e.g. /blog
#url: "https://mcshell.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
category_dir: categories
imagesite: img/khamardiuk.jpg
lsi: true
#layouts_dir: ../_layouts
#data_dir: ../_data
plugins: [jekyll-paginate-v2]
pagination:
  enable: true
  per_page: 10
  title: ':title - Page :num'
  limit: 0
  sort_field: 'date'
  sort_revers: true
  trail:
    before: 2
    after: 2

exclude: ['node_modules','gulpfile.js','package.json','package-lock.json','npm-debug.log','src','demo','dist']

  # Build settings
markdown: kramdown
# theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-admin
# Enable safe mode
safe: true

# Whitelist plugins under safe mode.
# Note that `some-other-jekyll-plugin` is not listed here. Therefore,
# it will not be loaded under safe mode.
whitelist:
  - jekyll-admin
