
# in the templates via {{ site.myvariable }}.
title: khamardiuk.com - Веб дизайнер
name: khamardiuk.com
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
 Новости , статьи , портфолио и многое другое
themecolor: #222
baseurl: "/" # the subpath of your site, e.g. /blog
#url: "https://khamardiuk.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
category_dir: categories
imagesite: img/khamardiuk.jpg
lsi: true
#layouts_dir: ../_layouts
#data_dir: ../_data
plugins: [jekyll-paginate-v2]
pagination:
  enable: true
  per_page: 10
  title: ':title - Страница :num'
  limit: 0
  sort_field: 'date'
  sort_revers: true
  trail:
    before: 2
    after: 2

exclude: ['node_modules','gulpfile.js','package.json','package-lock.json','npm-debug.log','src','demo','dist']

  # Build settings
markdown: kramdown
theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
